import {createRequire} from 'node:module';
import {mkdir,writeFile} from 'node:fs/promises';
import {fileURLToPath} from 'node:url';
import assert from 'node:assert/strict';
import {startPreview} from './wiring-ai-preview.mjs';
const runtime='C:/Users/james/.cache/codex-runtimes/codex-primary-runtime/dependencies/node/node_modules';
const {chromium}=createRequire(import.meta.url)(`${runtime}/playwright`);
const artifacts=fileURLToPath(new URL('./wiring-ai-preview-artifacts/',import.meta.url));
await mkdir(artifacts,{recursive:true});
const preview=await startPreview();
const report={preview:preview.url,fixture:'Synthetic images and mocked hooks; no production camera/Pi/model/storage',results:[],errors:[]};
const requestedScenario=process.argv.find(value=>value.startsWith('--scenario='))?.split('=')[1];
async function checkStepCanvas(page) {
  const canvas=page.locator('#current-step-diagram');
  assert.equal(await canvas.locator('h2').count(),1);
  assert.equal(await canvas.locator('.circuit-module-tabs').count(),0);
  assert.equal(await canvas.locator('.circuit-step-module').count(),1);
  const metrics=await canvas.evaluate(element=>{
    const viewport=element.querySelector('.circuit-viewport'),art=viewport.querySelector('.circuit-zoom-drawing');
    const box=node=>node.getBoundingClientRect().toJSON();
    return {canvas:box(element),viewport:box(viewport),art:box(art),scrollHeight:viewport.scrollHeight,
      clientHeight:viewport.clientHeight,scrollWidth:viewport.scrollWidth,clientWidth:viewport.clientWidth,
      shellScroll:element.scrollHeight,shellHeight:element.clientHeight};
  });
  assert(metrics.scrollHeight<=metrics.clientHeight+1,'Default diagram is cropped vertically');
  assert(metrics.scrollWidth<=metrics.clientWidth+1,'Default diagram is cropped horizontally');
  assert(metrics.shellScroll<=metrics.shellHeight+1,'Step shell requires scrolling just to see the full diagram');
  assert(metrics.viewport.height/metrics.canvas.height>=.6,'Diagram does not receive most of the step panel');
  assert(metrics.art.x>=metrics.viewport.x-1&&metrics.art.x+metrics.art.width<=metrics.viewport.x+metrics.viewport.width+1);
  assert(metrics.art.y>=metrics.viewport.y-1&&metrics.art.y+metrics.art.height<=metrics.viewport.y+metrics.viewport.height+1);
  assert(Math.max(metrics.art.width/metrics.viewport.width,metrics.art.height/metrics.viewport.height)>.9,'Canvas fit leaves avoidable empty space on both axes');
  return metrics;
}
let browser;
try{
  browser=await chromium.launch({headless:true,channel:'chrome'});
  for(const viewport of requestedScenario?[]:[{width:1365,height:1000},{width:1651,height:871},{width:390,height:844}]){
    const context=await browser.newContext({viewport,locale:'zh-TW'});
    const page=await context.newPage();
    const errors=[];page.on('pageerror',error=>errors.push(error.message));
    page.on('console',message=>{if(message.type()==='error')errors.push(message.text());});
    await page.goto(preview.url,{waitUntil:'networkidle'});
    assert(await page.locator('body').innerText(),`Fixture failed to mount: ${errors.join('\n')}`);
    assert.equal(await page.locator('vite-error-overlay').count(),0);
    const result={viewport,checks:[],metrics:{}};
    assert.deepEqual(await page.getByRole('navigation',{name:'作品工作流程'}).getByRole('button').allTextContents(),['01 設計與藍圖','02 接線引導＋AI 除錯','03 部署與執行']);
    result.checks.push('Three-stage workflow has no standalone debug navigation');
    const guideTab=page.getByRole('tab',{name:'接線引導',exact:true});
    const assistantTab=page.getByRole('tab',{name:'AI 協作',exact:true});
    assert.equal(await guideTab.getAttribute('aria-selected'),'true');
    assert.equal(await assistantTab.getAttribute('aria-selected'),'false');
    assert.notEqual(await guideTab.evaluate(element=>getComputedStyle(element).backgroundColor),await assistantTab.evaluate(element=>getComputedStyle(element).backgroundColor));
    result.checks.push('Right workspace initially shows the guide; AI is mounted but hidden');
    await page.evaluate(()=>{window.__qaCamera=document.querySelector('.video-shell');});
    const cameraBefore=await page.locator('.video-shell').boundingBox();
    const cameraTools=page.getByRole('button',{name:'相機工具',exact:true});
    const toolsPanel=page.getByRole('dialog',{name:'相機資訊與工具',exact:true});
    assert.equal(await page.locator('.main > .statusbar, .main > div > .statusbar').count(),0);
    assert.equal(await cameraTools.getAttribute('aria-expanded'),'false');
    await cameraTools.click();
    assert(await toolsPanel.isVisible());
    assert.deepEqual(await page.locator('.video-shell').boundingBox(),cameraBefore);
    const toolsBox=await toolsPanel.boundingBox();
    assert(toolsBox.x>=12&&toolsBox.x+toolsBox.width<=viewport.width-12);
    assert(toolsBox.y>=12&&toolsBox.y+toolsBox.height<=viewport.height-12);
    await toolsPanel.locator('.status-metrics').click();
    assert(await toolsPanel.isVisible());
    await toolsPanel.getByText('接線距離助手',{exact:true}).click();
    assert(await toolsPanel.getByText('隔離智慧調整替身',{exact:true}).isVisible());
    await page.screenshot({path:`${artifacts}/${viewport.width}-camera-tools.png`,fullPage:true});
    await page.keyboard.press('Escape');
    assert.equal(await toolsPanel.isVisible(),false);
    assert(await cameraTools.evaluate(element=>element===document.activeElement));
    await cameraTools.click();
    assert(await toolsPanel.getByText('隔離智慧調整替身',{exact:true}).isVisible());
    await toolsPanel.getByRole('button',{name:'切換鏡頭',exact:true}).click();
    assert.equal(await toolsPanel.isVisible(),false);
    assert.deepEqual(await page.evaluate(()=>window.__wiringQa.cameraActions),['camera']);
    await cameraTools.click();
    // Click a guaranteed outside point, not the camera's center: after adding
    // video controls the taller popover can legitimately cover that center.
    await page.mouse.click(2,2);
    assert.equal(await toolsPanel.isVisible(),false);
    // Playwright scrolls the tall phone page to click the camera center; compare
    // layout at the same scroll offset, not two different viewport positions.
    if(viewport.width<=960) await page.evaluate(()=>window.scrollTo(0,0));
    assert.deepEqual(await page.locator('.video-shell').boundingBox(),cameraBefore);
    assert.deepEqual(await page.evaluate(()=>window.__wiringQa.events),[]);
    result.checks.push('Camera tools move into the toolbar without a footer row or camera resize; panel stays viewport-bounded');
    result.checks.push('Tools survive closing; Escape restores focus, inside clicks stay open and outside clicks close');
    result.checks.push('Camera picker uses its original callback and closes the popup without hardware/API work');
    await page.screenshot({path:`${artifacts}/${viewport.width}-collapsed.png`,fullPage:true});
    assert(await page.getByRole('region',{name:'作品 Pin 接線引導'}).count()||await page.locator('.maker-project-guide').isVisible());
    await page.getByRole('button',{name:'我已接好，下一步 →',exact:true}).click();
    const beforeGuide=await page.locator('#qa-guide-state').textContent();
    assert.equal(JSON.parse(beforeGuide).index,1);
    assert.equal(Object.keys(JSON.parse(beforeGuide).confirmed).length,1);
    result.checks.push('Guide preserves original confirmation/next-step operation');
    await page.getByRole('button',{name:'上一步',exact:true}).click();
    const firstStep=JSON.parse(await page.locator('#qa-guide-state').textContent());
    assert.equal(firstStep.index,0);assert.equal(firstStep.phase,'active');assert.notEqual(firstStep.inspection,true);
    assert.deepEqual(firstStep.confirmed,JSON.parse(beforeGuide).confirmed);
    assert(await page.getByRole('button',{name:'上一步',exact:true}).isDisabled());
    assert.equal(await page.getByRole('button',{name:'返回接線',exact:true}).count(),0);
    await page.getByRole('button',{name:'下一步 →',exact:true}).click();
    assert.equal(await page.locator('#qa-guide-state').textContent(),beforeGuide);
    assert.deepEqual(await page.evaluate(()=>window.__wiringQa.events),[]);
    result.checks.push('Normal back returns directly to the preceding step, disables at step one and preserves confirmations without inspection');
    result.checks.push('Next on an already-confirmed step restores the same cursor and confirmation timestamp without hardware/model work');
    await page.getByRole('button',{name:'這一步需要幫忙',exact:true}).click();
    assert.equal(await assistantTab.getAttribute('aria-selected'),'true');
    await page.locator('.ai-debug-chat').waitFor();
    assert((await page.locator('.ai-debug-message').count())>=3);
    result.checks.push('Real AiDebugPanel history renders');
    const modes=page.getByRole('group',{name:'協作內容',exact:true});
    assert.equal(await modes.getByRole('button',{name:'問接法',exact:true}).getAttribute('aria-pressed'),'true');
    assert((await page.locator('.ai-debug-wiring-target').innerText()).includes('TRIG → Pin 11'));
    result.checks.push('Help opens the shared wiring conversation with the current TRIG / Pi Pin 11 context');
    await modes.getByRole('button',{name:'功能異常',exact:true}).click();
    assert.equal(await modes.getByRole('button',{name:'功能異常',exact:true}).getAttribute('aria-pressed'),'true');
    await modes.getByRole('button',{name:'問接法',exact:true}).click();
    assert.equal(await modes.getByRole('button',{name:'問接法',exact:true}).getAttribute('aria-pressed'),'true');
    const draft=page.locator('.ai-debug-entry textarea');
    await draft.fill('先保留這段草稿\nGND 要怎麼接？');
    const cameraAtStep=await page.locator('.video-shell').boundingBox();
    await page.getByRole('button',{name:'本步驟 2D 接線圖',exact:true}).click();
    assert(await page.locator('#current-step-diagram').isVisible());
    assert(await cameraTools.isVisible());
    await cameraTools.click();
    assert(await toolsPanel.isVisible());
    await toolsPanel.getByRole('button',{name:'收起相機資訊與工具',exact:true}).click();
    assert(await cameraTools.evaluate(element=>element===document.activeElement));
    assert.equal(await page.locator('.video-shell').isVisible(),false);
    assert.equal(await assistantTab.getAttribute('aria-selected'),'true');
    assert.equal(await draft.inputValue(),'先保留這段草稿\nGND 要怎麼接？');
    assert.equal(await page.locator('#qa-guide-state').textContent(),beforeGuide);
    assert.equal(await page.locator('#current-step-diagram [data-circuit-wire="hc-sr04:trig"].active').count(),1);
    assert((await page.locator('#current-step-diagram h2').innerText()).includes('TRIG → Pin 11'));
    result.metrics.stepCanvas=await checkStepCanvas(page);
    const stepNotes=page.locator('#current-step-diagram .circuit-workspace-notes');
    assert.equal(await stepNotes.getAttribute('open'),null);
    await stepNotes.locator('summary').click();
    assert(await stepNotes.getByText(/限 HC-SR04/).isVisible());
    await stepNotes.locator('summary').click();
    const stepViewport=page.locator('#current-step-diagram .circuit-viewport');
    await stepViewport.focus();await page.keyboard.press('+');
    assert.equal(await page.locator('#current-step-diagram .circuit-zoom-drawing').getAttribute('data-zoom'),'1.25');
    await page.keyboard.press('0');
    await checkStepCanvas(page);
    await page.locator('#current-step-diagram .circuit-zoom-toolbar').getByRole('button',{name:'放大接線圖 ↗',exact:true}).click();
    assert(await page.getByRole('dialog',{name:'放大接線圖',exact:true}).isVisible());
    await page.keyboard.press('Escape');
    assert.equal(await page.locator('dialog[open]').count(),0);
    assert.equal(await draft.inputValue(),'先保留這段草稿\nGND 要怎麼接？');
    assert.equal(await page.locator('#qa-guide-state').textContent(),beforeGuide);
    result.checks.push('Full-frame step uses one heading and one toolbar; the entire circuit fits both axes and most panel space belongs to the canvas');
    result.checks.push('Wiring notes, keyboard zoom/reset and the expanded diagram remain available without changing AI draft or manual progress');
    result.checks.push('Step diagram opens beside AI with the exact TRIG / Pin 11 wire, draft and confirmations preserved');
    if(viewport.width>960){
      const box=await page.locator('#current-step-diagram').boundingBox();
      assert(Math.abs(box.y-cameraAtStep.y)<2);
      assert(Math.abs(box.width-cameraAtStep.width)<2);
      assert(await page.getByRole('separator',{name:'調整鏡頭與接線引導寬度',exact:true}).isVisible());
      result.checks.push('2D uses the same desktop content row and adjustable column width as the camera');
    }
    await page.screenshot({path:`${artifacts}/${viewport.width}-step-diagram.png`,fullPage:true});
    await page.getByRole('button',{name:'返回鏡頭',exact:true}).click();
    assert(await page.locator('.video-shell').isVisible());
    assert(await page.evaluate(()=>window.__qaCamera===document.querySelector('.video-shell')));
    const cameraRestored=await page.locator('.video-shell').boundingBox();
    assert.equal(cameraRestored.width,cameraAtStep.width);
    assert.equal(cameraRestored.height,cameraAtStep.height);
    if(viewport.width<=960)await page.evaluate(()=>window.scrollTo(0,0));
    result.checks.push('Back to camera restores the same camera DOM and dimensions without model/hardware work');
    await assistantTab.focus();await page.keyboard.press('ArrowLeft');
    assert.equal(await guideTab.getAttribute('aria-selected'),'true');
    assert(await guideTab.evaluate(element=>element===document.activeElement));
    assert.equal(await page.locator('#qa-guide-state').textContent(),beforeGuide);
    await page.keyboard.press('End');
    assert.equal(await assistantTab.getAttribute('aria-selected'),'true');
    assert.equal(await draft.inputValue(),'先保留這段草稿\nGND 要怎麼接？');
    await page.getByRole('button',{name:'收合側邊面板',exact:true}).click();
    await page.getByRole('button',{name:'顯示側邊面板',exact:true}).click();
    assert.equal(await draft.inputValue(),'先保留這段草稿\nGND 要怎麼接？');
    assert(await page.evaluate(()=>window.__qaCamera===document.querySelector('.video-shell')));
    assert.deepEqual(await page.locator('.video-shell').boundingBox(),cameraBefore);
    result.checks.push('Keyboard tab switching and collapse/reopen preserve guide state, AI draft, camera DOM and dimensions');
    await draft.fill('');
    if(viewport.width>960){
      const splitter=page.getByRole('separator',{name:'調整鏡頭與接線引導寬度',exact:true});
      const originalWidth=(await page.locator('.wiring-workspace').boundingBox()).width;
      await splitter.focus();await page.keyboard.press('ArrowLeft');
      assert((await page.locator('.wiring-workspace').boundingBox()).width>originalWidth);
      await page.keyboard.press('Enter');
      assert(Math.abs((await page.locator('.wiring-workspace').boundingBox()).width-originalWidth)<2);
      assert(await page.evaluate(()=>window.__qaCamera===document.querySelector('.video-shell')));
      result.checks.push('Resize separator changes only pane width and resets without remounting the camera');
    }
    await page.getByRole('button',{name:'檢查紀錄',exact:true}).click();
    const records=page.getByRole('region',{name:'照片使用與檢查紀錄',exact:true});
    assert(await records.isVisible());
    await guideTab.click();await assistantTab.click();
    assert(await records.isVisible());
    await records.getByRole('button',{name:'返回對話',exact:true}).click();
    result.checks.push('Photo/check records keep their view across tabs and return to the same chat');
    assert.equal(await page.evaluate(()=>window.__wiringQa.events.length),0);
    result.checks.push('02 assistant intent switches locally without starting any model or hardware work');
    await page.getByRole('button',{name:'手動測試工具',exact:true}).click();
    const manual=page.getByRole('region',{name:'手動測試與程式工具',exact:true});
    assert.deepEqual(errors,[]);
    try{await manual.waitFor({state:'visible',timeout:3000});}catch(error){console.log(JSON.stringify(await page.locator('#debug-manual-tools').evaluate(element=>{const result=[];for(let node=element;node;node=node.parentElement){const style=getComputedStyle(node);result.push({tag:node.tagName,className:node.className,hidden:node.hidden,display:style.display,visibility:style.visibility,rect:node.getBoundingClientRect().toJSON()});}return result;})));throw error;}
    assert(await manual.getByRole('button',{name:'檢查 Pi 與程式紀錄',exact:true}).isVisible());
    await guideTab.click();await assistantTab.click();
    assert(await manual.isVisible());
    await manual.getByRole('button',{name:'返回對話',exact:true}).click();
    assert(await page.locator('.ai-debug-chat').isVisible());
    assert.equal(await page.getByRole('navigation',{name:'作品工作流程'}).getByRole('button',{name:'02 接線引導＋AI 除錯',exact:true}).getAttribute('aria-current'),'step');
    result.checks.push('Manual tools open and return to the same 02 conversation');
    const current=page.locator('.ai-diagram-card').filter({hasText:'設計接法 · v2'});
    const old=page.locator('.ai-diagram-card').filter({hasText:'設計接法 · v1'});
    assert.equal(await old.getByRole('button',{name:'前往此接線步驟'}).count(),0);
    result.checks.push('Historical v1 diagram has no link that changes the current wiring step');
    assert.equal(await current.locator('svg,.maker-circuit,dialog').count(),0);
    await current.getByRole('button',{name:'在左側查看接法',exact:true}).scrollIntoViewIfNeeded();
    const before=await page.evaluate(()=>({window:window.scrollY,main:document.querySelector('.main').scrollTop,chat:document.querySelector('.ai-debug-chat').scrollTop}));
    await current.getByRole('button',{name:'在左側查看接法',exact:true}).click();
    const left=page.locator('#current-step-diagram');
    await page.waitForTimeout(150);
    const after=await page.evaluate(()=>({window:window.scrollY,main:document.querySelector('.main').scrollTop,chat:document.querySelector('.ai-debug-chat').scrollTop}));
    result.metrics.diagramExpand={before,after};
    if(viewport.width>960){assert.equal(after.window,before.window,'Desktop link forced page scroll');assert.equal(after.main,before.main,'Desktop link forced main scroll');}
    assert.equal(await assistantTab.getAttribute('aria-selected'),'true');
    assert.equal(await page.locator('#qa-guide-state').textContent(),beforeGuide);
    result.checks.push('AI link opens the main diagram and retains the AI tab and guide cursor');
    assert.equal(await left.locator('[data-circuit-wire="hc-sr04:trig"].active').count(),1);
    await left.getByRole('button',{name:'查看完整電路',exact:true}).click();
    const modules=left.locator('[data-circuit-module]');
    const moduleIds=async()=>modules.evaluateAll(elements=>elements.map(element=>element.getAttribute('data-circuit-module')).sort());
    assert.deepEqual(await moduleIds(),['hc-sr04','mrd-tf240-8p-cs']);
    assert.equal(await left.locator('[data-circuit-wire].active').count(),0);
    result.checks.push('View full circuit displays both HC and TFT without a forced AI selection');
    const moduleTabs=left.getByRole('group',{name:'篩選接線模組',exact:true});
    await moduleTabs.getByRole('button',{name:'MRD-TFT240',exact:true}).click();
    assert.deepEqual(await moduleIds(),['mrd-tf240-8p-cs']);
    await moduleTabs.getByRole('button',{name:'全部零件',exact:true}).click();
    assert.deepEqual(await moduleIds(),['hc-sr04','mrd-tf240-8p-cs']);
    result.checks.push('TFT module filter and All modules both work with controlled selection cleared');
    await left.getByRole('button',{name:'放大接線圖 ↗',exact:true}).click();
    assert.equal(await page.locator('dialog[open] [data-circuit-module]').count(),2);
    await page.screenshot({path:`${artifacts}/${viewport.width}-full-circuit.png`});
    await page.keyboard.press('Escape');
    await left.getByRole('button',{name:'返回 AI 指出的接線',exact:true}).click();
    assert.deepEqual(await moduleIds(),['hc-sr04']);
    assert.equal(await left.locator('[data-circuit-wire="hc-sr04:trig"].active').count(),1);
    assert.equal(await current.getByRole('button',{name:'HC · TRIG',exact:true}).getAttribute('aria-pressed'),'true');
    result.checks.push('Return to AI referenced wire restores HC TRIG focus after browsing full circuit');
    const viewportDiagram=left.getByRole('region',{name:'可縮放接線圖'}).first();
    await viewportDiagram.focus();
    await page.keyboard.press('+');
    assert.equal(await left.locator('.circuit-zoom-drawing').first().getAttribute('data-zoom'),'1.25');
    result.checks.push('Referenced TRIG highlighted; keyboard zoom works');
    const expandButton=left.getByRole('button',{name:'放大接線圖 ↗',exact:true});
    await expandButton.click();
    assert.equal(await page.locator('dialog[open]').count(),1);
    await page.screenshot({path:`${artifacts}/${viewport.width}-diagram.png`,fullPage:true});
    await page.keyboard.press('Escape');
    assert.equal(await page.locator('dialog[open]').count(),0);
    assert(await expandButton.evaluate(element=>element===document.activeElement));
    result.checks.push('Expanded diagram dialog closes using Escape and restores trigger focus');
    const photo=page.locator('.ai-photo-card');
    await photo.getByRole('button',{name:'Pi Pin 特寫',exact:true}).click();
    assert((await photo.locator('img').getAttribute('src')).includes('view=pi_pins'));
    await photo.getByRole('button',{name:'零件旋正放大',exact:true}).click();
    assert((await photo.locator('img').getAttribute('src')).includes('view=component_reading'));
    assert.equal(await photo.locator('a').getAttribute('target'),'_blank');
    await photo.screenshot({path:`${artifacts}/${viewport.width}-photo.png`});
    result.checks.push('Multi-view tabs use own image endpoint; original opens separately');
    for(const [label,region] of [['01 設計與藍圖','隔離設計頁'],['03 部署與執行','隔離部署頁']]){
      await page.getByRole('button',{name:label,exact:true}).click();
      assert(await page.getByRole('region',{name:region,exact:true}).isVisible());
      assert.equal(await page.locator('.debug-page').count(),0);
      await page.getByRole('button',{name:'02 接線引導＋AI 除錯',exact:true}).click();
      assert((await page.locator('.ai-debug-chat').innerText()).includes('本輪照片是模擬測試資料'));
    }
    result.checks.push('01/02/03 navigation preserves conversation and keeps debug workspace only in 02');
    await page.locator('.ai-diagram-card').filter({hasText:'設計接法 · v2'}).getByRole('button',{name:'在左側查看接法',exact:true}).click();
    const guideAfter=JSON.parse(await page.locator('#qa-guide-state').textContent());
    assert.notEqual(guideAfter.inspection,true);
    assert.deepEqual(guideAfter.confirmed,JSON.parse(beforeGuide).confirmed);
    result.checks.push('Viewing a diagram never enters guide inspection or confirms a wire');
    await page.locator('#current-step-diagram').getByRole('button',{name:'返回目前步驟',exact:true}).click();
    assert.equal(await assistantTab.getAttribute('aria-selected'),'true');
    assert((await page.locator('.ai-debug-chat').innerText()).includes('本輪照片是模擬測試資料'));
    assert.equal(await page.getByRole('navigation',{name:'作品工作流程'}).getByRole('button',{name:'02 接線引導＋AI 除錯',exact:true}).getAttribute('aria-current'),'step');
    await page.getByRole('button',{name:'返回鏡頭',exact:true}).click();
    result.checks.push('Return to current step/camera leaves the conversation inside 02');
    result.metrics.layout=await page.evaluate(()=>({width:innerWidth,documentWidth:document.documentElement.scrollWidth,bodyWidth:document.body.scrollWidth,localStorageKeys:Object.keys(localStorage),chat:document.querySelector('.ai-debug-chat')?.getBoundingClientRect().toJSON()}));
    result.metrics.caption=await page.locator('.ai-diagram-card > p').last().evaluate(element=>({foreground:getComputedStyle(element).color,background:getComputedStyle(element.parentElement).backgroundColor}));
    assert(result.metrics.layout.documentWidth<=viewport.width,'Horizontal document overflow');
    result.metrics.workspace=await page.locator('.wiring-workspace').boundingBox();
    result.metrics.camera=await page.locator('.video-shell').boundingBox();
    result.metrics.composer=await page.locator('.ai-debug-entry').boundingBox();
    result.metrics.chat=await page.locator('.ai-debug-chat').boundingBox();
    result.metrics.content=await page.locator('.debug-page-content').evaluate(element=>({padding:getComputedStyle(element).padding,border:getComputedStyle(element).borderTopWidth}));
    assert.deepEqual(result.metrics.content,{padding:'0px',border:'0px'});
    if(viewport.width>960){
      assert(result.metrics.workspace.x>=result.metrics.camera.x+result.metrics.camera.width,'Workspace not beside the camera');
      assert(Math.abs(result.metrics.workspace.y+result.metrics.workspace.height-result.metrics.camera.y-result.metrics.camera.height)<2,'Workspace and camera bottoms misaligned');
      assert(result.metrics.workspace.y+result.metrics.workspace.height<=viewport.height,'Workspace extends beyond desktop viewport');
    }else{
      assert(result.metrics.workspace.y>=result.metrics.camera.y+result.metrics.camera.height,'Narrow screen workspace overlaps the camera');
    }
    assert(result.metrics.chat.height>=90,'No usable conversation height');
    assert(result.metrics.composer.y+result.metrics.composer.height<=result.metrics.workspace.y+result.metrics.workspace.height,'Composer is clipped by the workspace');
    result.checks.push('Bounded right-side chat and composer; desktop side-by-side and narrow-screen stacked layout');
    assert.deepEqual(result.metrics.layout.localStorageKeys,[]);
    assert.deepEqual(errors,[]);
    result.checks.push('No browser errors, document overflow or localStorage writes');
    await page.screenshot({path:`${artifacts}/${viewport.width}-wiring.png`,fullPage:true});
    await modes.getByRole('button',{name:'功能異常',exact:true}).click();
    await page.screenshot({path:`${artifacts}/${viewport.width}-debug.png`,fullPage:true});
    await guideTab.click();
    await page.evaluate(()=>{window.__qaBackCamera=document.querySelector('.video-shell');});
    const eventsBeforeBack=await page.evaluate(()=>window.__wiringQa.events);
    for(let step=1;step<4;step++) await page.getByRole('button',{name:'我已接好，下一步 →',exact:true}).click();
    const completed=JSON.parse(await page.locator('#qa-guide-state').textContent());
    assert.equal(completed.phase,'review');assert.equal(completed.index,3);
    assert.equal(Object.keys(completed.confirmed).length,4);
    assert.equal(await page.getByRole('button',{name:'回看',exact:true}).count(),0);
    await page.getByRole('button',{name:'上一步',exact:true}).click();
    const lastStep=JSON.parse(await page.locator('#qa-guide-state').textContent());
    assert.deepEqual(lastStep,{...completed,phase:'active'});
    assert((await page.locator('.guide-step-label').innerText()).includes('4 / 4'));
    assert.equal(await page.getByRole('button',{name:'返回接線',exact:true}).count(),0);
    await page.screenshot({path:`${artifacts}/${viewport.width}-previous-step.png`,fullPage:true});
    await page.getByRole('button',{name:'上一步',exact:true}).click();
    const priorStep=JSON.parse(await page.locator('#qa-guide-state').textContent());
    assert.deepEqual(priorStep,{...completed,phase:'active',index:2});
    await page.getByRole('button',{name:'下一步 →',exact:true}).click();
    await page.getByRole('button',{name:'下一步 →',exact:true}).click();
    assert.deepEqual(JSON.parse(await page.locator('#qa-guide-state').textContent()),completed);
    assert.deepEqual(await page.evaluate(()=>window.__wiringQa.events),eventsBeforeBack);
    assert(await page.evaluate(()=>window.__qaBackCamera===document.querySelector('.video-shell')));
    assert.deepEqual(errors,[]);
    assert(await page.evaluate(()=>document.documentElement.scrollWidth<=innerWidth));
    result.checks.push('Completed-module back returns to its last wire; further back/next preserves all four records and returns to the same overview');
    result.checks.push('Completed back/next does not remount the camera, invoke hardware/model APIs, add browser errors or horizontal overflow');
    report.results.push(result);await context.close();
  }
  for(const viewport of [{width:1365,height:1000},{width:390,height:844}])for(const scenario of requestedScenario?[requestedScenario]:['hc','tft','repair','trial','2d','prepare']){
    const context=await browser.newContext({viewport,locale:'zh-TW'});
    const page=await context.newPage();const errors=[];
    page.on('pageerror',error=>errors.push(error.message));page.on('console',message=>{if(message.type()==='error')errors.push(message.text());});
    await page.goto(`${preview.url}?scenario=${scenario}`,{waitUntil:'networkidle'});
    assert(await page.locator('body').innerText(),`Scenario ${scenario} failed: ${errors.join('\n')}`);
    const result={viewport,scenario,checks:[]};
    assert.equal(await page.getByRole('button',{name:'02 接線引導＋AI 除錯',exact:true}).getAttribute('aria-current'),'step');
    if(scenario==='2d'){
      assert(await page.locator('.maker-2d-main').isVisible());
      assert.equal(await page.locator('.video-shell').isVisible(),false);
      const saved=await page.locator('#qa-guide-state').textContent();
      await page.evaluate(()=>{window.__qaCamera=document.querySelector('.video-shell');});
      await page.getByRole('tab',{name:'AI 協作',exact:true}).click();
      assert(await page.locator('.maker-2d-main').isVisible());
      assert.equal(await page.locator('.video-shell').isVisible(),false);
      const draft=page.locator('.ai-debug-entry textarea');
      await draft.fill('保留此問題：目前這條線接哪裡？');
      await page.locator('#qa-request-capture').evaluate(element=>element.click());
      assert(await page.locator('.video-shell').isVisible());
      assert(await page.getByRole('button',{name:'本步驟 2D 接線圖',exact:true}).isEnabled());
      await page.getByRole('button',{name:'本步驟 2D 接線圖',exact:true}).click();
      assert(await page.locator('#current-step-diagram').isVisible());
      assert((await page.locator('#current-step-diagram [role=status]').innerText()).includes('等待實物照片'));
      await page.locator('#qa-request-capture').evaluate(element=>element.click());
      assert(await page.locator('.video-shell').isVisible());
      assert.equal(await draft.inputValue(),'保留此問題：目前這條線接哪裡？');
      await page.locator('#qa-finish-capture').evaluate(element=>element.click());
      assert(await page.locator('#current-step-diagram').isVisible());
      assert.equal(await draft.inputValue(),'保留此問題：目前這條線接哪裡？');
      result.checks.push('Only an explicit mocked capture temporarily reveals the camera, then restores 2D and the AI draft');
      await page.getByRole('tab',{name:'接線引導',exact:true}).click();
      assert(await page.locator('.maker-2d-main').isVisible());
      assert.equal(await page.locator('#qa-guide-state').textContent(),saved);
      await page.getByRole('button',{name:'我已接好，下一步 →',exact:true}).click();
      assert.equal(await page.locator('#current-step-diagram [data-circuit-wire="hc-sr04:trig"].active').count(),1);
      assert((await page.locator('#current-step-diagram h2').innerText()).includes('TRIG → Pin 11'));
      result.checks.push('Confirming the next guide step updates the highlighted wire and both pin labels in 2D');
      const confirmedStep=JSON.parse(await page.locator('#qa-guide-state').textContent());
      await page.getByRole('button',{name:'上一步',exact:true}).click();
      assert.equal(await page.locator('#current-step-diagram [data-circuit-wire="hc-sr04:gnd"].active').count(),1);
      assert.deepEqual(JSON.parse(await page.locator('#qa-guide-state').textContent()).confirmed,confirmedStep.confirmed);
      await page.getByRole('button',{name:'下一步 →',exact:true}).click();
      assert.deepEqual(JSON.parse(await page.locator('#qa-guide-state').textContent()),confirmedStep);
      assert.equal(await page.locator('#current-step-diagram [data-circuit-wire="hc-sr04:trig"].active').count(),1);
      result.checks.push('Back/next in 2D follows the same cursor, updates the diagram and preserves confirmation timestamps without inspection');
      assert(await page.evaluate(()=>window.__qaCamera===document.querySelector('.video-shell')));
      assert.equal(await page.evaluate(()=>window.__wiringQa.events.length),0);
      result.checks.push('AI tab switching preserves 2D preference and guide state without hardware/model work');
      await page.locator('.guide-module-track button').nth(1).click();
      await page.getByRole('button',{name:'開始接線 →',exact:true}).click();
      assert.equal(await page.locator('#current-step-diagram [data-circuit-module="mrd-tf240-8p-cs"]').count(),1);
      assert.equal(await page.locator('#current-step-diagram [data-circuit-module="hc-sr04"]').count(),0);
      result.tftCanvas=await checkStepCanvas(page);
      assert.equal(await page.evaluate(()=>window.__wiringQa.events.length),0);
      await page.screenshot({path:`${artifacts}/${viewport.width}-tft-step-canvas.png`,fullPage:true});
      result.checks.push('Switching to TFT fits all eight header pins and Pi routes inside the same full-frame canvas without hardware/model work');
    }else if(scenario==='prepare'){
      assert(await page.getByText('準備開始接線',{exact:true}).isVisible());
      assert.equal(await page.locator('.wiring-workspace-context small').count(),0);
      assert.equal(await page.locator('.guide-panel-body .component-test-card').count(),0);
      await page.getByRole('button',{name:'問 AI 接法',exact:true}).click();
      assert.equal(await page.getByRole('tab',{name:'AI 協作',exact:true}).getAttribute('aria-selected'),'true');
      assert.equal(await page.evaluate(()=>window.__wiringQa.events.length),0);
      result.checks.push('Before wiring starts, shared header has no premature step or test result; asking AI remains a local navigation action');
    }else if(scenario==='hc'){
      await page.getByRole('button',{name:'手動測試工具',exact:true}).click();
      const tools=page.getByRole('region',{name:'手動測試與程式工具',exact:true});
      await tools.getByRole('button',{name:'準備好了，取樣 5 秒',exact:true}).click();
      await tools.getByRole('button',{name:'停止本次測試',exact:true}).click();
      assert.deepEqual(await page.evaluate(()=>window.__wiringQa.events.filter(event=>event.kind==='test').map(event=>event.action)),['near','stop']);
      result.checks.push('HC current-run sample/stop controls call the exact mocked run from 02 manual tools');
      await tools.getByRole('button',{name:'返回對話',exact:true}).click();
      assert(await page.locator('.ai-debug-chat').isVisible());
    }else if(scenario==='tft'){
      const test=page.locator('.ai-debug-panel .component-test-card');
      const confirm=test.getByRole('button',{name:'確認顯示結果',exact:true});
      assert(await confirm.isDisabled());
      assert.equal(await test.locator('input[type=radio]:checked').count(),0);
      await test.getByRole('radio',{name:'1234',exact:true}).check();
      assert(await confirm.isDisabled());
      await test.getByRole('checkbox',{name:'紅、綠、藍三色正常',exact:true}).check();
      await confirm.click();
      assert.deepEqual(await page.evaluate(()=>window.__wiringQa.events.filter(event=>event.kind==='test')),[{kind:'test',id:'qa-mrd-tf240-8p-cs',action:'visual',data:{code:'1234',appearance:'normal'}}]);
      result.checks.push('TFT confirmation remains in 02 chat and requires both human code selection and RGB confirmation');
    }else if(scenario==='repair'){
      const repair=page.locator('.ai-debug-panel .debug-agent');
      await repair.getByText('候選修改差異／離線測試',{exact:true}).click();
      assert((await repair.innerText()).includes('+ limit = 20'));
      await repair.getByRole('button',{name:'套用修復並試跑',exact:true}).click();
      assert.equal(await page.evaluate(()=>window.__wiringQa.events.length),0);
      const confirmation=repair.getByRole('group',{name:'確認草稿變更',exact:true});
      await confirmation.getByRole('button',{name:'取消',exact:true}).click();
      assert.equal(await confirmation.count(),0);
      await repair.getByRole('button',{name:'套用修復並試跑',exact:true}).click();
      await confirmation.getByRole('button',{name:'確認執行',exact:true}).click();
      const apply=await page.evaluate(()=>window.__wiringQa.events.find(event=>event.kind==='debug'&&event.body?.action==='apply'));
      assert.equal(apply.path,'debug/cases/qa-case/actions');assert.equal(apply.body.candidate_id,'qa-candidate');assert.equal(apply.body.confirmed,true);
      result.checks.push('Repair diff and offline checks render inline in 02; only explicit confirmation applies the exact candidate');
    }else{
      const trial=page.locator('.ai-debug-panel .debug-trial-result');
      const confirm=trial.getByRole('button',{name:'送出本次目視確認',exact:true});assert(await confirm.isDisabled());
      await trial.getByRole('checkbox').check();await confirm.click();
      const visual=await page.evaluate(()=>window.__wiringQa.events.find(event=>event.kind==='debug'&&event.body?.action==='visual'));
      assert.equal(visual.path,'debug/trials/qa-trial/actions');assert.equal(visual.body.observed,true);
      result.checks.push('Current 60-second trial result stays in 02 and requires explicit human observation');
      await page.getByRole('button',{name:'手動測試工具',exact:true}).click();
      const tools=page.getByRole('region',{name:'手動測試與程式工具',exact:true});
      await tools.getByRole('button',{name:'開始 60 秒試跑',exact:true}).click();
      assert(await page.evaluate(()=>window.__wiringQa.events.some(event=>event.kind==='debug'&&event.path==='debug/trials'&&event.body.request_id)));
      result.checks.push('60-second trial scheduling control remains available in 02 manual tools');
    }
    assert.equal(await page.getByRole('button',{name:'02 接線引導＋AI 除錯',exact:true}).getAttribute('aria-current'),'step');
    assert.deepEqual(errors,[]);assert.deepEqual(await page.evaluate(()=>Object.keys(localStorage)),[]);
    assert(await page.evaluate(()=>document.documentElement.scrollWidth<=innerWidth));
    result.checks.push('Scenario remains in 02 without browser errors, storage writes or horizontal overflow');
    await page.screenshot({path:`${artifacts}/${viewport.width}-${scenario}.png`,fullPage:true});
    report.results.push(result);await context.close();
  }
}catch(error){report.errors.push(error.stack);throw error;}
finally{
  await writeFile(`${artifacts}/report.json`,JSON.stringify({...report,requests:preview.requests},null,2));
  await browser?.close();await new Promise(resolve=>preview.server.close(resolve));
  console.log(JSON.stringify(report,null,2));
}
